version: "3.4"
services:

        node:
            build: .
            volumes:
                - ./container-files:/home/node
            user: node
            working_dir: /home/node 
            env_file: 
                - .react.env
                - .node.env
            networks:
                node_network:
                  aliases:
                    - frontend
                    - backend


networks:
    node_network:
