version: "3.4"
services:

        node:
            build: .
            volumes:
                - ./node:/home/node
            user: node
            working_dir: /home/node 
            env_file: .env
            ports:
                - ${REACT_APP_PORT}:3000
